# Server Port
server.port=5000

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root
spring.datasource.password=foulae0101@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

# Redis Config
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

# Set a 32+ byte secret key
jwt.secret=abcdefghijklmnopqrstuvwxyz123456
jwt.universal_secret=zyxwvutsrqponmlkjihgfedcba654321

# CORS Allowed Origins
cors.allowed-origins=http://localhost:5173

# Image Folder
app.image.folder=/Users/admin/Java/prathisthan/Server/static/images

# Static Resource Locations
spring.web.resources.static-locations=file:src/main/resources/static/

